### ISSUE TITLE
Certificate Error on website

### ISSUE THREAD

**Issue by leovanalphen** [vDesk-Cloud/vDesk#1]
Hi,

You have an incorrect cert on your vdesk.cloud website. Looks like you're using a self-signed cert?
![Annotation](https://user-images.githubusercontent.com/7933690/79222004-105ce780-7e57-11ea-9218-fbc48b6109c1.png)

**Comment by vDesk-Cloud** [comment]
Forgot to click on "use Let's encrypt" in the Pleskpanel. ;-)
